var level1 = ["x                 =x",
              "x          o       x",
              "x          o       x",
              "x    o xxxxx    xxxx",
              "x   xx             x",
              "x         o      o x",
              "xxx o     x   xxxxxx",
              "x    xx           =x",
              "x                  x",
              "xxxx     xx       @x",
              "x              xxxxx",
              "x   o              x",
              "x o       xx       x",
              "xxx     xx         x",
              "x o        o  o  o x",
              "xxxx      xxxxxxxxxx",
              "x                   ",
              "x!!!!!!!!!!x        ",
              "xxxxxxxxxxxx        ",
              "                    "];
