var level1 = ["x                 =                     =x",
              "x          o                 o         xxx",
              "x          o         xxxxxx              x",
              "x    o xxxxx    xxxxx     xxxxx      xxxxx",
              "x   xx             ==                     ",
              "x         o                               ",
              "x         o      o                        ",
              "xxx o     x     xxxxxxx                   ",
              "x    xx           =x               xx     ",
              "x                           xxxx          ",
              "xxxx     xx       @                       ",
              "x              xxxxx                      ",
              "x   o              x",
              "x o       xx       x",
              "xxx     xx         x",
              "x o        o  o  o x",
              "xxxx      xxxxxxxxxx",
              "x                   ",
              "x!!!!!!!!!!x        ",
              "xxxxxxxxxxxx        ",
              "                    ",
              "                    ",
              "                    ",
              "                    ",
              "                    ",
              "                    "];
